### PR TITLE
Signature to detect document files creating network traffic

### PR DESCRIPTION
**Pull request by kevross33**
This is my first conversion sig to 2.0 so please check although it appears to work fine and is the start of me trying to convert some of the signatures from cuckoo-modified over into cuckoo-2.0 so at least a start has been made. The signature is to convert the ideas from this signature:
https://raw.githubusercontent.com/spender-sandbox/community-modified/master/modules/signatures/network_docfile_http.py

If the above link can be used to verifiy the logic of this signature before commit then that would be best given this is my first cuckoo 2.0 signature and also my pythons skills are fine but needs an expert eye :-) I intend to start the conversion process as I can because as previously discussed in general there is a lot of excellent signatures and while I may not manage everything at least it helps out with what I can.

### CODE REVIEW

**Comment by kevross33** [comment]
doc_network_example

**Comment by jbremer** [comment]
Awesome @kevross33. This is actually something I wanted to discuss with you, so thanks a lot for initiating this by yourself.
I'll definitely assist with any Python cleanup and related issue etc, so please keep the PRs coming ;-)

**Comment by kevross33** [comment]
Yeah no problem. Hopefully if I can get a good number of things over tidying them up then should be simpler and it will help reduce workload so they can focus on other things :-)

**Comment by kevross33** [comment]
btw here is a nice example of an older office downloader. You can clearly see the network data and also it reading in an EXE file.

doc_downloader

**Comment by kevross33** [comment]
closing as putting together with some others

**Pull request closed without merging**
