### PR TITLE
Add in signature for creating ransomware message

### PR DESCRIPTION
**Pull request by kevross33**
This is a conversion of this signature I put together for cuckoo-modified https://github.com/spender-sandbox/community-modified/pull/157. The concerns that were raised during my initial submission of that signature around performance for looking at every NTWriteFile call stands for this signature. On the other one I got round the performance issues by:
- For NTWriteFile only looking for bootkit modifications
- For files actually written to disk looking through dropped files as cuckoo-modified shows the first 4KB.
- NtWriteFile doesn't actually show the written file name it seems in the cuckoo 2.0 reports, just buffer and filehandle.

With this one however I am closer to my original sig but with some performance and accuracy improvements but I have tested with ransomware & it works fine.

### CODE REVIEW

**Comment by jbremer** [comment]
I can add the `filepath` to each `NtWriteFile` call if you like :-)

**Comment by kevross33** [comment]
Yeah that would be great information to have for some of the marking of calls/IOCs. To actually get the performance stuff & so I could split the sig I would also need the first 4KB text file to be extracted into the report like cuckoo-modified would help too otherwise I need to stick with the NtWriteFile method. If I had the 4KB I would have it written like the modified sig of:

- Look for writing to physicaldisk & harddisk for bootkits (Satana ransomware for example)
- Then for text files (with extracted text) search for ASCII Text. This actually gets text, html, vbs etc. I could check filename for extensions with NtWriteFile like .html. text etc but it might end up with a long list and a false negative risk.

When I have been testing and I have checked this sig against TeslaCrypt, Maktub, Cerber & Bart ransomwares and it works a treat though. Thanks.

**Comment by jbremer** [comment]
Also keep in mind that we log buffers bigger than 4kb (iirc) to the `dropped buffers`, so those should be treated separately. If a `NtWriteFile` call has a `dropped buffer` then you'll be able to find the sha1 hash of the file in the `dropped` key of the call (i.e., `call["dropped"]` iirc).

**Comment by kevross33** [comment]
Made some more improvements. I will look for other improvements too I can make for this. How do you think it is currently looking or is there other things I can do with it?

**Pull request merged**
