### PR TITLE
Add in recon_programs signature

### PR DESCRIPTION
**Pull request by kevross33**
Add in converted signature from cuckoo-modified:

https://github.com/spender-sandbox/community-modified/blob/master/modules/signatures/recon_programs.py

### CODE REVIEW

**Comment by jbremer** [comment]
This one could use some more work :-)

**Comment by kevross33** [comment]
What do you want to see in it? It does work unless you just want it to list out the programs as iocs rather than marking the API calls doing this?

**Comment by jbremer** [comment]
It should probably be rewritten to use the `self.check_key()` functionality in `on_complete` :-)

**Comment by kevross33** [comment]
I don't think that will return as good results. i.e here is the information for Program Microsoft Visual C++ 2010 x64 Redistributable - 10.0.40219. If it was just the key that was used the value of the actual program wouldn't be shown. If you want I could mark it as an IOC instead with program on the left and then the value on the right of the program?

key_handle: 0x000001dc 
regkey_r: DisplayName 
reg_type: 1 (REG_SZ) 
value: Microsoft Visual C++ 2010 x64 Redistributable - 10.0.40219 
regkey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{1D8E6291-B0D5-35EC-8441-6616F567A0F7}\DisplayName

**Comment by kevross33** [comment]
FYI best sample for this is Dridex if you want to have a look yourself.

**Comment by jbremer** [comment]
That's a good argument. I've been thinking about the best way to keep these values associated with the registry key IOCs, but haven't really found *the* way yet. I'm open for suggestions :-)

**Comment by kevross33** [comment]
being able to grab the value for a key as an IOC so it will go fetch it could be useful. Still for now I think this is suitable as it is still a clean result

**Comment by jbremer** [comment]
Until I come up with a more generic method to also keep track of the value, this Signature is fine - thanks!

**Comment by jbremer** [comment]
(Merged it manually.. seems Git history was messed up due to some rebasing, but it's in there).

**Pull request closed without merging**
