### PR TITLE
Add more TTPs to persistence_autorun.py

### PR DESCRIPTION
**Pull request by keizn77**
The regex in this signature can capture multiple TTPs.

### CODE REVIEW

**Comment by doomedraven** [comment]
this is a very bad idea, you just put them all in one place, the best would be split them so each part would have it own ttp

**Comment by keizn77** [comment]
Sorry for the late reply. I know this is a bad idea, but I'm not sure whether I can split this signature into multiple signatures or not. If it's allowed, I will try it.

**Comment by doomedraven** [comment]
Any improvement is allowed, if not you just will spam with fake ttps

**Comment by keizn77** [comment]
OK, I'll do it. Thank you!

**Pull request closed without merging**
