### PR TITLE
Create new sig for querying for username

### PR DESCRIPTION
**Pull request by kevross33**

### CODE REVIEW

**Comment by jbremer** [comment]
Could you add `GetUserNameW` and `GetUserNameExA/W`? :-)

**Comment by kevross33** [comment]
I can. Is the user_name field still present across these APIs as I don't have examples and the microsoft documention isn't helping me: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724435%28v=vs.85%29.aspx. 

LookupAccountName is another one I will likely need to look at too.

**Comment by kevross33** [comment]
I am thinking of the fields btw for network communication sig I just did which utilises these fields as we want good coverage

**Comment by jbremer** [comment]
Actually I changed this slightly just yesterday https://github.com/cuckoosandbox/monitor/commit/3494044a9a7be92f73ed6b8238aa1117323c54eb. For backwards compatibility `user_name` might be easier, though (now it's all `username` while Signatures should work for both variations, ideally).
What do you think?

**Comment by kevross33** [comment]
Ok sounds fine, so it is just a case of leaving it as user_name for now? Is this the same across all the API calls mentioned here? When you see the network_c2 sig I am building from this idea you will see why; if I can get all the common queried data appearing in network data being sent, crypto calls etc it could allow for understanding how information is added in and also identifying it is constructing C2 in the first place.

Try running that sig though against a Dridex sample; it works well although I need to do a lot more testing and building of it to get it right (then I need to look at getting it over to cuckoo-modified once it is done :-D)

**Comment by kevross33** [comment]
removing this. FP prone

**Pull request closed without merging**
