### PR TITLE
Create signature for malware checking for clipboard data (i.e for san…

### PR DESCRIPTION
**Pull request by kevross33**
…dbox detection)

### CODE REVIEW

**Comment by kevross33** [comment]
I can't see in monitor sigs GetClipboardData being hooked so if this signature is wanted to be used this hook will need to be added

**Comment by jbremer** [comment]
Thanks! Good suggestion, I'll be adding it soon :-)

**Comment by jbremer** [comment]
If in the meantime you have any malware (hashes) that would trigger it, do let me know :)

**Comment by kevross33** [comment]
yeah sure. I will gather them up once I have checked they display this
behaviour. Sorry I would add hooks myself but still trying to wrap my head
around that with little time to do so as few more I want and some
investigation I want to try for getting data out.

**Comment by jbremer** [comment]
@kevross33 You got any of those hashes? :-)

**Comment by kevross33** [comment]
https://www.hybrid-analysis.com/sample/41d63d293a6e2722fcf82f8bf67b8f566bd4d3f669ede146ccc286f0228d8f62?environmentId=100

**Comment by kevross33** [comment]
That above file should do it. It certainly has that capability it is just a case of triggering it but it does load in GetClipboardData  from user32 module. That said there also seems to be an issue with it following the execution chain but I am not sure why yet

**Comment by kevross33** [comment]
Example (my concern being it may miss the GetClipBoard use):

Cuckoo modified:
image

image

Cuckoo 2.0:
image

image

**Comment by jbremer** [comment]
Merged, thanks! Checking hashes & analyses later.

**Pull request closed without merging**
