### PR TITLE
Create sig for writing EXE (and generic code sig) to memory of another process

### PR DESCRIPTION
**Pull request by kevross33**
Seen in Dridex MD5 2eaf243bad4b1c22089e7654524f0e5a

### CODE REVIEW

**Comment by kevross33** [comment]
image

**Comment by kevross33** [comment]
You can also write memory with NtWow64WriteVirtualMemory64 which is missing from being hooked.

**Comment by kevross33** [comment]
On the sig for generic write which I have left as severity 2 it could be a severity 3 and very reliable if there was a way to make sure the process it is not writing to is a child process and it would be more reliable to code injection then

**Comment by jbremer** [comment]
Merged, thanks! Checking hash later.

**Pull request closed without merging**
