### PR TITLE
Create signature for removing downloaded file evidence

### PR DESCRIPTION
**Pull request by kevross33**
Conversion of existing cuckoo-modified signature:

https://github.com/spender-sandbox/community-modified/blob/master/modules/signatures/removes_zoneid_ads.py

### CODE REVIEW

**Comment by jbremer** [comment]
How about using the `file_deleted` summary item for this? :-)

**Comment by kevross33** [comment]
is there that? I can't see deleted files in my summary on this; only accessed and written.

**Comment by kevross33** [comment]
on another note where is up to date cuckoo 2.0 signature documentation with all the options?

**Comment by kevross33** [comment]
never mind I found it :-) Also changed the signature now to use the suggested feature

**Pull request merged**
