### PR TITLE
Create signature for network traffic for injection

### PR DESCRIPTION
**Pull request by kevross33**
This is a signature I am testing about system processes appearing in the process tree and generating network traffic which is possibly from code injection and seems to be the case in my testing. I also intend to do one with these appearing in the processes but not as a child process again indicative of injection without having to detect the injection itself.

### CODE REVIEW

**Comment by kevross33** [comment]
Goznym Example: 
image

Hesperbot Connectivity Checks:
image

**Comment by kevross33** [comment]
Better hesperberbot example following changes (the good thing is here the CnC structure is visible even though the traffic never resulted in traffic in this test so only APIs were visible.

image

**Comment by kevross33** [comment]
Tinba Example:

image

**Comment by jbremer** [comment]
Merged, thanks!

**Pull request closed without merging**
