### PR TITLE
Add in signature to detect HTTP CnC traffic features

### PR DESCRIPTION
**Pull request by kevross33**
Converted cuckoo-modified signature:

https://github.com/spender-sandbox/community-modified/blob/master/modules/signatures/network_cnc_http.py

### CODE REVIEW

**Comment by jbremer** [comment]
You'd be able to do much more by using the extended HTTP information, through `get_net_http_ex`, which is a reconstruction of the entire TCP/HTTP stream rather than just the first packet.

**Comment by kevross33** [comment]
I have changed this sig to use get_net_http_ex now; simplified the signature and also made it so that the features that are suspicious are grouped against the actual request rather than just an overall list and requests to make it easier to understand what is odd about each request (once other features have been added).

Pony:
image

Hesperbot:
image

**Comment by kevross33** [comment]
Here is another example for Pony after being dropped by a malicious doc:

image

**Comment by kevross33** [comment]
Add in signature for HTTP POST

image

**Comment by jbremer** [comment]
Merged, thanks!

**Pull request closed without merging**
