### PR TITLE
Add in sig to detect disabling UAC

### PR DESCRIPTION
**Pull request by kevross33**
Cuckoo-modified sig:

https://github.com/spender-sandbox/community-modified/blob/master/modules/signatures/disables_uac.py

### CODE REVIEW

**Comment by jbremer** [comment]
What about https://github.com/cuckoosandbox/community/blob/master/modules/signatures/windows/disables_security.py ? :-)

**Comment by botherder** [comment]
It is already covered, although I'm not sure about that signature. I'm thinking it's too generic and we miss value in not being specific about what feature has been disabled.

**Comment by kevross33** [comment]
I will have a look at see what can be done when I have a chance with the idea being (hopefully) if the key is marked:

**Comment by kevross33** [comment]
ok accidentally commented. Anyway the idea is that instead of marking self.mark_ioc("registry", regkey) it will do self.mark_ioc("disabled windows firewall", regkey) or something along those lines pulling each bit from what they are going.

**Comment by kevross33** [comment]
closing this as have changed original signature to better communicate individual changes.

**Pull request closed without merging**
