### PR TITLE
Update Virtual Box Registry keys

### PR DESCRIPTION
**Pull request by kevross33**
Changes brought over from cuckoo-modified

https://github.com/spender-sandbox/community-modified/blob/master/modules/signatures/antivm_vbox_keys.py

### CODE REVIEW

**Comment by jbremer** [comment]
Perhaps an idea to strip some of the trailing dollar signs?

**Comment by kevross33** [comment]
How come if that is the complete key and we aren't checking any further so wish to terminate the check

**Comment by jbremer** [comment]
Cuckoo uses `re.match()` internally, so if there is trailing information *after* what is matched by the regex, then `re.match()` would return no results, because the pattern does not match the content completely. Hence my proposal to strip off the dollar signs - where required.

**Comment by kevross33** [comment]
Ah ok. I have noticed this on the AV sig. Updating :D

**Comment by kevross33** [comment]
Does $ need removed on all File and Regex based matches? Because I have submitted ones there I did but noticed it in others too that have been implemented by cuckoo and I understood from your comment in the indicator lists $ should be removed from end?

**Comment by jbremer** [comment]
Merged, thanks!

**Pull request closed without merging**
